version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: booking-service-db
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - booking-service-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: booking-service-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - booking-service-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  booking-service-network:
    driver: bridge
